# Generated by Django 3.1.1 on 2020-11-04 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0008_auto_20201010_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('ap_hi', models.IntegerField()),
                ('ap_lo', models.IntegerField()),
                ('cholesterol', models.IntegerField()),
                ('gluc', models.IntegerField()),
                ('smoke', models.IntegerField()),
                ('alco', models.IntegerField()),
                ('active', models.IntegerField()),
                ('output', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='diabetesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 4, 23, 37, 23, 773053)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
    ]
