# Generated by Django 3.1.1 on 2020-11-07 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0009_auto_20201104_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiomodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 19, 0, 5, 574946)),
        ),
        migrations.AlterField(
            model_name='diabetesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 7, 19, 0, 5, 574001)),
        ),
    ]
