# Generated by Django 3.1.1 on 2020-11-13 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0010_auto_20201107_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 13, 13, 40, 808705)),
        ),
        migrations.AlterField(
            model_name='cardiomodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 13, 13, 40, 809729)),
        ),
        migrations.AlterField(
            model_name='diabetesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 13, 13, 13, 40, 808705)),
        ),
    ]
