# Generated by Django 3.1.1 on 2020-11-14 19:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ml', '0011_auto_20201113_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiomodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardiomodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 1, 29, 4, 192358)),
        ),
        migrations.AlterField(
            model_name='diabetesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 1, 29, 4, 191362)),
        ),
        migrations.AlterField(
            model_name='heartmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 1, 29, 4, 191362)),
        ),
    ]
