# Generated by Django 3.1.1 on 2020-11-21 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0014_auto_20201121_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diabetesmodel',
            name='age',
        ),
        migrations.AlterField(
            model_name='breastmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 12, 34, 915782)),
        ),
        migrations.AlterField(
            model_name='cardiomodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 12, 34, 915782)),
        ),
        migrations.AlterField(
            model_name='diabetesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 12, 34, 914741)),
        ),
        migrations.AlterField(
            model_name='heartmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 18, 12, 34, 914741)),
        ),
    ]
