# Generated by Django 3.1.1 on 2020-11-22 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0015_auto_20201121_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardiomodel',
            old_name='ap_hi',
            new_name='arterial_pressure_hi',
        ),
        migrations.RenameField(
            model_name='cardiomodel',
            old_name='ap_lo',
            new_name='arterial_pressure_lo',
        ),
        migrations.AlterField(
            model_name='breastmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 10, 18, 21, 682849)),
        ),
        migrations.AlterField(
            model_name='cardiomodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 10, 18, 21, 683846)),
        ),
        migrations.AlterField(
            model_name='diabetesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 10, 18, 21, 681849)),
        ),
        migrations.AlterField(
            model_name='heartmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 10, 18, 21, 682849)),
        ),
    ]
