# Generated by Django 3.1.1 on 2020-11-22 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0017_auto_20201122_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardiomodel',
            old_name='arterial_pressure_hi',
            new_name='arterial_pressure_high',
        ),
        migrations.RenameField(
            model_name='cardiomodel',
            old_name='arterial_pressure_lo',
            new_name='arterial_pressure_low',
        ),
        migrations.RenameField(
            model_name='diabetesmodel',
            old_name='DPF',
            new_name='Diabetes_Pedigree_Function',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='ca',
            new_name='Chest_Pain',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='chol',
            new_name='Exercise_Thallium_heart',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='cp',
            new_name='Exercise_induced_angina',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='exang',
            new_name='Fasting_blood_sugar',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='fbs',
            new_name='Maximum_heart_rate',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='restecg',
            new_name='Resting_electrocardiographic_results',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='oldpeak',
            new_name='ST_depression',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='slope',
            new_name='Systolic_blood_pressure',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='thal',
            new_name='cholesterol',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='thalach',
            new_name='major_vessels',
        ),
        migrations.RenameField(
            model_name='heartmodel',
            old_name='trestbps',
            new_name='slope_of_ST_segment',
        ),
        migrations.AlterField(
            model_name='breastmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 10, 50, 58, 324296)),
        ),
        migrations.AlterField(
            model_name='cardiomodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 10, 50, 58, 325293)),
        ),
        migrations.AlterField(
            model_name='diabetesmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 10, 50, 58, 323296)),
        ),
        migrations.AlterField(
            model_name='heartmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 10, 50, 58, 324296)),
        ),
    ]
